spring:
  profiles:
    active: local
  application:
    name: schedule-management
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  jackson:
    time-zone: "Asia/Seoul"
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  web:
    resources:
      add-mappings: false
  cloud:
    aws:
      credentials:
        accessKey: 1
        secretKey: 1

server:
  port: 9898
  servlet.context-path: /

---
# local 환경 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/SCHEDULE_MANAGER?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: admin
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: schedule-management
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    log-request-details: true

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug
    com.schedule: debug
    com.netflix.discovery: WARN
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace